// export { default as HomeAdmin } from './admin/home';
export { default as HomeAdmin } from './admin/homeAdmin';
export { default as AllVideo } from './admin/homeAdmin';
export { default as Download } from './admin/download';
export { default as Calendar } from './admin/calendar/Pessoal';
export { default as CalendarConector } from './admin/calendar/Conector';
export { default as Team } from './admin/profile/Team';
export { default as AllClients } from './admin/client/AllClients';
export { default as Profession } from './admin/database/Profession';
export { default as Perfil } from './admin/profile/Perfil';
export { default as Client } from './admin/profile/Client';
export { default as CursoCreate } from './admin/curso/create';
export { default as Notifications } from './admin/notifications';
export { default as Chat } from './admin/chat';
export { default as Certification } from './admin/certification';
export { default as StatementAdmin } from './admin/statement';

export { default as Cursos } from './client/cursos';
export { default as CursoInfo } from './client/cursoInfo';
export { default as Home } from './client/home';
export { default as Statement } from './client/statement';
export { default as Video } from './client/modules';
