// export { default as HomeAdmin } from './admin/home';
export { default as HomeAdmin } from './admin/video';
export { default as AllVideo } from './admin/video';
export { default as Video } from './admin/video/modules';
export { default as Download } from './admin/download';
export { default as Calendar } from './admin/calendar/Pessoal';
export { default as CalendarConector } from './admin/calendar/Conector';
export { default as Home } from './client/home';
export { default as Team } from './admin/profile/Team';
export { default as AllClients } from './admin/client/AllClients';
export { default as Profession } from './admin/database/Profession';
export { default as Perfil } from './admin/profile/Perfil';
