import { darken, fade } from "@material-ui/core/styles";
export default {
  palette: {
    type: 'light',
    primary: {
      main: '#387b85',
      mainBlue: '#38568a',
      mainGreen: '#387b85',
      mainPurple: '#b9bbea',
      mainOrange: '#dc8035',
      mainLight: '#ddd8d2',
      contrastText: '#fff',
    },
    secondary: {
      main: '#990000',
    },
    background: {
      paper: '#fff',
      paperModal: '#fafafa',
      default: '#e4dfdb',
      paperHighlight: '#387b8533',
      inactive: '#a3a3a9',
      line: '#A8A8B355',
      hoverPaper: '#c0c2c250',
      attention: '#eb3b33',
      attentionHover: '#bf2407',
      // nav: '#f1eeeb',
      nav: '#fff',
      drawer: '#1a1a1e',
    },
    table: {
      hover: '#eee',
      textCell: '#1a1a1e',
      textHeader: '#fff',
      checkboxBack: '#fff',
      line: '#ccc',
      header: '#26262A',
      everyOtherRow: '#fafafa',
    },
    text: {
      dark: '#000',
      light: '#fff',
      primary: '#000',
      secondary: '#303035',
      third: '#97969b',
      tabsText: '#303035',
      primaryNav: '#00000088',
    },
    status: {
      success: '#5cb85c',
      fail: '#bb2011',
      warn: '#cfd220',
      info: '#5bc0de',
      successD: '#1fb913',
      failD: '#880000',
      warnD: '#b59c0e',
      infoD: '#4e91d4',
      orange: '#F37735',
    },
    notification: {
      back: '#fff',
      shadow: '#00000088',
      text: '#353539',
    },
    drawer: {
      listTitle: '#fff',
      icon: '#7d7c85',
      textListInactive: '#7d7c85',
      // arrowOpen: '#d9560b',
      arrowOpen: '#387b85',
      textListSelected: '#387b85',
      circleSelected: '#1b1c21cc',
      textSubListInactive: 'blue',
      textSubListSelected: '#5b5a5f',
      textSubListActive: '#387b85',
      hoverSubListOpen: '#c0c2c250',
      backgroundListOpen: 'transparent',
      backgroundSubSubListOpen: 'transparent',
      hoverSubSubListOpen: '#c0c2c250',
      subSubListActive: '#d9560b12',
    },
  },
};

